language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2

install: "mvn process-resources --settings .travis.settings.xml"

script: "mvn verify --settings .travis.settings.xml --quiet"

jdk:
  - oraclejdk8
