language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.zinc

install: mvn process-resources --settings .travis.settings.xml

script:
  - mvn verify --settings .travis.settings.xml
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

jdk:
  - oraclejdk8
