language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.zinc

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version
  - mvn compile -Ptravis --quiet --fail-never --update-snapshots --settings .travis.settings.xml -e
  - mvn test-compile -Ptravis --quiet --fail-never --update-snapshots --settings .travis.settings.xml -e

script:
  - mvn verify -Ptravis --update-snapshots --settings .travis.settings.xml -e
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

jdk: oraclejdk8
